[package]
name = "cargo-sysroot"
version = "0.4.1"
authors = ["Diana"]
#
readme = "README.md"
repository = "https://github.com/HobbyistRust/cargo-sysroot"
description = "Simply and Easily cross-compile the Rust sysroot crates."
license = "MIT OR Apache-2.0"
keywords = [
    "sysroot",
    "libcore",
    "no_std",
    "cross",
    "compilation",
]
categories = [
    "no-std",
    "embedded",
    "development-tools",
    "development-tools::cargo-plugins",
]

[dependencies]
toml = "0.4.10"
serde_derive = "1.0.82"
serde = "1.0.82"
fs_extra = "1.1.0"
clap = "2.32.0"

[badges]
maintenance = { status = "as-is" }
